feat: github action is workign trying to add log from dockerfile if some test fail

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -16,4 +16,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Start containers
-        run: docker-compose -f "docker-compose.yml" up -d --build
+        run: |
+          docker-compose -f "docker-compose.yml" up -d --build
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "Docker Compose up failed, printing logs..."
+            docker-compose logs
+            exit $EXIT_CODE
+          fi
+
+      - name: Cleanup
+        if: always()
+        run: docker-compose down
